### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by qckev** [jkralicky/TTT-End-Round-Music#2]
To actually hear something you have to play the song and then set the play volume. It happens when a round end or when I play something from playurl.

**Comment by kralicky** [comment]
@JSimo

**Comment by JSimo** [comment]
@qckev @jkralicky Will take a look this weekend.

**Comment by qckev** [comment]
Alright thank you

**Comment by JSimo** [comment]
@qckev @jkralicky Should be fixed now. (Patch is in the latest pull request). 100% tested and verified on a server.

**Comment by qckev** [comment]
Thank you! It works.
