### ISSUE TITLE
Superadmins can't hear music (?)

### ISSUE THREAD

**Issue by tsirolnik** [jkralicky/TTT-End-Round-Music#5]
So, first of all, props for creating this mod.
Now, I've added this mod to my server, it does work for everyone, except... You guessed right - Me.
I have no idea why it is not working, the music volume level is maxed, End round music is enabled and etc
I've checked the console but nothing appears

**Comment by kralicky** [comment]
Open your volume mixer and check to make sure Awesomium volume is not muted. Otherwise I'm not sure. I haven't worked on this stuff in months. Feel free to have someone else take a look and send a pull request with fixed code if needed.

**Comment by NanoAi** [comment]
Hello I would like to talk to you in private but I can't seem to find your email any where please msg me back.

**Comment by kralicky** [comment]
cobalt77@gmx.com
